### ISSUE TITLE
Code Coverage - Vector3

### ISSUE THREAD

**Issue by hardiksachan** [ShatteredSoftware/ShatteredCore#27]
RE: #20 

Hey, I would like to write unit tests for `Vector3`. If that's okay, please assign me this issue.

**Comment by hardiksachan** [comment]
Hey, there is no definition for `unaryMinus` in `Vector3`. Do you mind if I add it?

**Comment by hhenrichsen** [comment]
Go for it. Do try to keep code changes to Vector3 in a separate commit if possible, and follow the [commit format](https://github.com/ShatteredSoftware/ShatteredCore/blob/main/CONTRIBUTING.md#commit-format); I've updated that document since you last contributed.
