### ISSUE TITLE
More Common Conversions

### ISSUE THREAD

**Issue by hhenrichsen** [ShatteredSoftware/ShatteredCore#7]
We should create more common conversions/predicates. 

Ideas:
- [x] `HasItemPredicate` - Extends (or requires) `SenderPlayerPredicate`, ensures sender has an item.
- [x] `ProviderPredicate` - Takes a `Provider<Boolean>` and ensures it's true.
- [ ] `NearColumnPredicate` - Extends (or requires) `SenderPlayerPredicate`, Takes either a `Provider<Location>` or a `Location` and a radius, ensures the sender is within a given radius, ignoring y coordinates.
- [ ] `NearLocationPredicate` - Extends (or requires) `SenderPlayerPredicate`, Takes either a `Provider<Location>` or a `Location` and a radius, ensures the sender is within a given radius.

Any one of these could be a pull request, and should be pretty simple.

**Comment by mscibilia** [comment]
Hi, I would like to work on some of these. Just some clarification on HasItemPredicate, does that mean does the sender have an item in hand or has an item in their inventory?

**Comment by hhenrichsen** [comment]
@mscibilia I was envisioning it as in their inventory, but a version that looks for an item in their hand would probably be just as useful. Keep them in separate PRs if you do decide to do them.
